name: Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"

      - name: Update and install dependencies
        run: |
          composer update
          composer install --prefer-dist --no-progress

      - name: Start PHP development server
        run: composer dev &

      - name: Wait for server to start
        run: sleep 5

      - name: Run Integration Tests
        run: composer test:integration

      - name: Stop PHP development server
        run: pkill -f "php -S" || true
